name: Auto Commit and Push

on:
  schedule:
    - cron: :*/10 * * * *

jobs:
      - name: Set up Git
        run: |
          git config user.name "saaaaaka"  # Git ユーザー名を設定
          git config user.email "kka449783@gmail.com"  # Git メールアドレスを設定

      - name: Make changes (example)
        run: |
          echo "Some changes" >> images/render_image.png # 変更を加える
          git add images/render_image.png  # 変更を追加

      - name: Commit changes
        run: |
          git commit -m "Automated commit: Added example.txt" || echo "No changes to commit"  # 変更があればコミット

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions トークンを使用して認証
        run: |
          git push origin main  # リモートの main ブランチにプッシュ
