name: Auto Commit and Push

on:
  schedule:
    - cron: "＊/1 ＊ ＊ ＊ ＊"  # 10分ごとに実行

jobs:
  auto-commit-and-push:
    runs-on: ubuntu-latest
    enviroment: update

    steps:
      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Git 設定
      - name: Upgate Data
        run: |
          git config user.name "saaaaaka"  # Gitユーザー名を設定
          git config user.email "kka449783@gmail.com"  # Gitメールアドレスを設定
          git add images/render_image.png # 任意のファイルに変更を加える
          git commit -m "Automated commit: Changes made by GitHub Actions" || echo "No changes to commit
          git push origin main
