name: Auto Add and Commit and Push

on:
  push:
    branches: [ main ]  # mainブランチにプッシュされた際にトリガーされます

jobs:
  auto_commit_push:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # リポジトリのコードをチェックアウト

      - name: Set up Git
        run: |
          git config user.name "saaaaaka"  # Gitユーザー名を設定
          git config user.email "kka449783@gmail.com"  # Gitメールアドレスを設定

      - name: Verify the current state
        run: |
          git status  # 現在の状態を確認 
